import { sql } from "drizzle-orm";
import {
  check,
  index,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

import { checkpointDecisionEnum } from "./enums.js";
import { projects } from "./projects.js";
import { screenshots } from "./screenshots.js";
import { testRuns } from "./test_runs.js";
import { users } from "./users.js";

/**
 * Append-only log of reviewer decisions, one row per checkpoint (a
 * `screenshots` row) decided. A checkpoint's *effective* state is
 * `decision ?? verdict` over its single **active** row (`reverted_at IS NULL`);
 * undoing an action stamps `reverted_at`/`reverted_by` on its rows rather than
 * deleting them, so history is never lost.
 *
 * `action_id` is generated by the client and groups every row written by one
 * user action (a bulk or group approve touches many checkpoints). `before`
 * holds the undo snapshot (`decisionSnapshotSchema` in `@furan/shared-types`);
 * NULL means the decision cannot be undone (legacy / backfilled rows).
 *
 * `project_id` is the RLS key (`checkpoint_decisions_isolation`, ADR-058 /
 * migration 0033 pattern; the policy is appended by hand in migration 0035).
 */
export const checkpointDecisions = pgTable(
  "checkpoint_decisions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    runId: uuid("run_id")
      .notNull()
      .references(() => testRuns.id, { onDelete: "cascade" }),
    screenshotId: uuid("screenshot_id")
      .notNull()
      .references(() => screenshots.id, { onDelete: "cascade" }),
    actionId: uuid("action_id").notNull(),
    decision: checkpointDecisionEnum("decision").notNull(),
    // NULL = legacy / system (backfill, deleted user).
    actorId: uuid("actor_id").references(() => users.id, {
      onDelete: "set null",
    }),
    // Closed set enforced by `checkpoint_decisions_source_chk`; mirrors
    // `decisionSourceSchema` in `@furan/shared-types`.
    source: text("source").notNull(),
    before: jsonb("before"),
    // clock_timestamp() (not now()) so rows written in one transaction keep
    // their insertion order at microsecond resolution (consistent with ADR-068).
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`clock_timestamp()`),
    revertedAt: timestamp("reverted_at", { withTimezone: true }),
    revertedBy: uuid("reverted_by").references(() => users.id, {
      onDelete: "set null",
    }),
  },
  (t) => ({
    /** The DB guarantees at most one active decision per checkpoint. */
    activeUniq: uniqueIndex("checkpoint_decisions_active_uniq")
      .on(t.screenshotId)
      .where(sql`${t.revertedAt} IS NULL`),
    actionIdx: index("checkpoint_decisions_action_idx").on(t.actionId),
    runIdx: index("checkpoint_decisions_run_idx").on(t.runId),
    projectCreatedIdx: index("checkpoint_decisions_project_created_idx").on(
      t.projectId,
      // `.nullsFirst()` is Postgres's default for DESC, so the index is a plain
      // `created_at DESC` (drizzle-kit would otherwise emit DESC NULLS LAST,
      // which `ORDER BY created_at DESC` cannot use). created_at is NOT NULL.
      t.createdAt.desc().nullsFirst(),
    ),
    sourceCheck: check(
      "checkpoint_decisions_source_chk",
      sql`${t.source} IN ('viewer', 'batch', 'group', 'sdk', 'inbox', 'backfill')`,
    ),
  }),
);

export type CheckpointDecisionRow = typeof checkpointDecisions.$inferSelect;
export type NewCheckpointDecisionRow = typeof checkpointDecisions.$inferInsert;
